### ISSUE TITLE
Simple ESP circuit?

### ISSUE THREAD

**Issue by MagnusErler** [Asbjoern/ESPHome-Kamstrup-Radius#1]
Is it possible to just connect an ESP module to GND, VCC and DATA_OUT, or do I need a (complicated) circuit like this [https://github.com/Asbjoern/Kamstrup-Radius-Interface/tree/master/pcb](https://github.com/Asbjoern/Kamstrup-Radius-Interface/tree/master/pcb)?

**Comment by Asbjoern** [comment]
If you power the esp module externally and don’t connect vcc. Then yes. 
There is not enough power supplied by the meter for the peak currents of the esp module. 
There is a risk of damaging the meter if you draw more current than allowed. That is why I have this circuit to limit the current drawn and a supercap for the peak currents.
